package com.kevmayo.chalkie.events;

public enum EventType {

	STROKE_ADDED,
	STROKE_REMOVED,
	MANAGER_ADDED,
	MANAGER_READY,
	SAVE_BUTTON_PRESSED,
    LOAD_COMPLETE, ADDED, REGISTER_EVENT, REMOVED, LAUNCH_BUTTON_PRESSED
}
